# community-engine config file
# Copyright (C) 2021. violet-team. Licensed under the Apache-2.0 License.

server_port: 8864

redis:
  # single or cluster
  mode: single
  nodes:
    - host: 127.0.0.1
      port: 6379

mongo:
  connect: mongodb://127.0.0.1:27017